### ISSUE TITLE
Parsing Issue: Not Parsing Old Portals?

### ISSUE THREAD

**Issue by pcaddict08** [pcaddict08/IPST2#10]
FW: Hello, it seems IPST2 parse not Portal Status E-Mails more then nearly 1400 days ago.

IPST(1): 206 accepted Portals (oldest; 1493 days, youngest 653 days), IPST2: 191 accepted Portals (oldest: 1394 days, youngest: 5 days), same Database (E-Mail Folder).

Here an example of a E-Mail that IPST2 not parse (no portal image in E-Mail):

MIME-Version: 1.0
X-Received: by 10.182.113.136 with SMTP id iy8mr1062320obb.43.1375921388263; Wed, 07 Aug 2013 17:23:08 -0700 (PDT)
Reply-To: Ingress Support <ingress-support@google.com>
X-Google-Appengine-App-Id: s~betaspike
X-Google-Appengine-App-Id-Alias: betaspike
Message-ID: <089e0153737a961bbc04e364a981@google.com>
Date: Thu, 08 Aug 2013 00:23:08 +0000
Subject: Ingress Portal Live: DREWAG Eichendorfer Straße
From: Ingress Support <ingress-support@google.com>
To: Befagor <spookie2k@gmail.com>
Content-Type: multipart/alternative; boundary=089e0153737a961bac04e364a97e

--089e0153737a961bac04e364a97e
Content-Type: text/plain; charset=ISO-8859-1; format=flowed; delsp=yes

Success! Your Portal candidate has been accepted and will be enabled in the  
Ingress Scanner in the near future. Once the Portal is activated, it may  
take up to two weeks for XM production to commence around the Portal. For  
additional information, please visit the Ingress Intel Map or our Help  
Center.

--089e0153737a961bac04e364a97e
Content-Type: text/html; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable

<p>Success! Your Portal candidate has been accepted and will be enabled in =
the Ingress Scanner in the near future. Once the Portal is activated, it ma=
y take up to two weeks for XM production to commence around the Portal. For=
 additional information, please visit the <a href=3D"http://ingress.com/int=
el">Ingress Intel Map</a> or our <a href=3D"http://support.google.com/ingre=
ss">Help Center</a>.</p>
--089e0153737a961bac04e364a97e--

**Comment by ShadowHawk54** [comment]
Solved in recent update. Portals without pictures were colliding in the database, and the format of old portals wasn't being caught.
