### ISSUE TITLE
Parsing Issue: Some Rejections Aren't Caught

### ISSUE THREAD

**Issue by pcaddict08** [pcaddict08/IPST2#12]
IPST2 Can't See This

From: Ingress Operations <ingress-support@nianticlabs.com>
Date: 2017-06-18 13:14 GMT+02:00
Subject: Portal review complete: Momument Aux Morts
To: mgs3 <loganmgs@gmail.com>

We've reviewed your Portal submission and believe it meets the Candidate Portal criteria. However, this candidate is too close to an existing Portal, so we're not able to bring it online at this time.

-NianticOps

Momument Aux Morts
21 Rue Principale, 68600 Weckolsheim, France

**Comment by ShadowHawk54** [comment]
Solved in recent update
