### ISSUE TITLE
Parsing Issue: Submission Date Sometimes Not Set

### ISSUE THREAD

**Issue by pcaddict08** [pcaddict08/IPST2#13]
IPST Isn't setting submission date.

---------- Forwarded message ----------
From: Ingress Operations <ingress-support@nianticlabs.com>
Date: 2017-06-19 14:25 GMT+02:00
Subject: Portal review complete: Autoroute Paris Rhin Rhone
To: joeshua <l.c.honore@gmail.com>

We've reviewed your Portal submission and given the information you've provided in your submission, we have decided not to accept this candidate.

At this time, we’re not able to provide specific rejection reasons for each submission we review; however, the following are common reasons for rejection:

The candidate is on our PLEASE DON'T SUBMIT list
We couldn't find evidence that the candidate meets any of our ACCEPTANCE CRITERIA
The candidate was submitted in an incorrect location, and we weren't able to find the right location
-NianticOps

Autoroute Paris Rhin Rhone
L'Arverne, 18340 Lissay-Lochy, France

**Comment by ShadowHawk54** [comment]
Should be solved in recent update. In some cases though, I noticed the portal title in the submission email didn't match the portal title in the response email. This seems to be a problem with Niantic not properly supporting UTF-8
