### ISSUE TITLE
Fix Search function

### ISSUE THREAD

**Issue by jimmymho** [pcaddict08/IPST2#7]
I'm noticing a number of weird behaviors when searching/filtering the portal lists. This list may grow or shrink as I reproduce them better, but I just want to jot things down for now.

- When you type in something to search, the list updates correctly, but when you click on any portal from the filtered list, it displays the wrong portal--it looks like it displays the portal from the original, unfiltered list. 
- If you type in something that should return zero results, like "zzzzzz", the list doesn't refresh correctly. Ex: "z" will display "Razzoo's", "Baccus Plaza", and "Spring Creek Gazebo"; "zz" will further narrow it down to only "Razzoo's"; but then "zzz" will continue showing "Razzoo's", instead of an empty list. 
- Maybe more...

**Comment by pcaddict08** [comment]
Fixed this.
